FROM golang:1.18 as build
RUN go install github.com/cortesi/modd/cmd/modd@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
WORKDIR /app
COPY go.mod .
COPY go.sum .
CMD modd
